sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: 59.110.215.216
    port: 3306
    database: hmdp
    username: root
    password: 123
  redis:
    host: 59.110.215.216
    port: 6379
    database: 0
    password: 123
  rabbitmq:
    host: 59.110.215.216 # 主机名
    port: 5672            # 端口
    virtual-host: /dianping  # 虚拟主机
    username: dianping      # 用户名
    password: 123