
server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: hmdp
  datasource:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?useSSL=false
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

  redis:
    #host: 10.67.11.194
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    #database: ${sky.redis.database}
   # password: ${sky.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    timeout: 10000ms
  rabbitmq:
      host: ${sky.rabbitmq.host}
      port: ${sky.rabbitmq.port}
      virtual-host: ${sky.rabbitmq.virtual-host}
      username: ${sky.rabbitmq.username}
      password: ${sky.rabbitmq.password}
aliyun_oss:
  endpoint:  ${sky.aliyun_oss.endpoint}
  accessKeyId:   ${sky.aliyun_oss.accessKeyId}
  accessKeySecret:   ${sky.aliyun_oss.accessKeySecret}
  bucketName:   ${sky.aliyun_oss.bucketName}

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug